// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFAg2QtYuFeSB52YP0n5_lXW3xPm4DSQc',
    appId: '1:765764649697:android:6d44847453c019d9a22da0',
    messagingSenderId: '765764649697',
    projectId: 'chat-box-cbfef',
    databaseURL: 'https://chat-box-cbfef-default-rtdb.firebaseio.com',
    storageBucket: 'chat-box-cbfef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2qfcm_yrjBKQ4iomAVn0Nfl92AxjFAPw',
    appId: '1:765764649697:ios:b53e5a95a3f2dc10a22da0',
    messagingSenderId: '765764649697',
    projectId: 'chat-box-cbfef',
    databaseURL: 'https://chat-box-cbfef-default-rtdb.firebaseio.com',
    storageBucket: 'chat-box-cbfef.appspot.com',
    androidClientId: '765764649697-jpr2k4ar5kma527equffcvfvf9btnen0.apps.googleusercontent.com',
    iosClientId: '765764649697-mbml55tpiun4impqdk9f7110gect4f8h.apps.googleusercontent.com',
    iosBundleId: 'com.app.chatBox',
  );
}
