import 'package:flutter/material.dart';

class AppList {
  static Map userData = {
    "userData": [
      {"image": "assets/images/home_sto_four.png", "data": "My status"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
      {"image": "assets/images/home_sto_three.png", "data": "Adil"},
      {"image": "assets/images/home_sto_two.png", "data": "Marina"},
      {"image": "assets/images/home_sto_one.png", "data": "Dean"},
      {"image": "assets/images/home_sto.png", "data": "Max"},
    ],
  };
  static final List<Map<String, dynamic>> newUser = [
    {"botam": "assets/images/botam_one.png", "data1": "Alex Linderson", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": "Team Align", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "John Ahraham", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": "Sabila Sayma", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "John Borino", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "Angel Dayna", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_one.png", "data1": " Borino", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": " Dayna", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "Sabila ", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": " Linderson", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "John", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "Angel ", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_one.png", "data1": "Alex ", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": " Align", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": " Ahraham", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": " Sayma", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "Johnorino B", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "Angel", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": "Team", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "JoAhraham", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": "SabilaSay", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "Jorino", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "ADayna", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_one.png", "data1": "rino", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": "AngelDaya", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "SaSayma", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": "derson", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "Jono", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "gelDayna", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_one.png", "data1": "Alexson", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": "Telign", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "JAhraham", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": "SSayma", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "JBorino", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "ADayna", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": "TAlign", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "hraham", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": "bilaSayma", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "Jono", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "Ana", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_one.png", "data1": "rino", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": "Ayna", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "Sama", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": "lexLinderson", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "hkno", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "yna", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_one.png", "data1": "Anderson", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_two.png", "data1": "amAli", "data2": "Don’t miss to attend the meeting.", "data3": "2 min ago"},
    {"botam": "assets/images/botam_three.png", "data1": "aham", "data2": "Hey! Can you join the meeting?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_four.png", "data1": "Sama", "data2": "How are you today?", "data3": "2 min ago"},
    {"botam": "assets/images/botam_five.png", "data1": "ino", "data2": "Have a good day 🌸", "data3": "2 min ago"},
    {"botam": "assets/images/botam_six.png", "data1": "l Dayna", "data2": "How are you today?", "data3": "2 min ago"},
  ];

  static Map callUser = {
    "callUser": [
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_two.png", "titleOne": "Team Align", "treOne": "Today, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "Today, 07:30 AM"},
      {"imageOne": "assets/images/botam_four.png", "titleOne": "Sabila Sayma", "treOne": "Yesterday, 07:35 PM"},
      {"imageOne": "assets/images/botam_one.png", "titleOne": "Alex Linderson", "treOne": "Monday, 09:30 AM"},
      {"imageOne": "assets/images/botam_three.png", "titleOne": "John Ahraham", "treOne": "03/07/22, 07:30 AM"},
      {"imageOne": "assets/images/botam_five.png", "titleOne": "John Borino", "treOne": "Monday, 09:30 AM"},
    ],
  };
  static Map settingUser = {
    "settingUser": [
      {"iconOne": Icons.security, "titleOne": "Account", "treOne": "Privacy, security, change number"},
      {"iconOne": Icons.chat_outlined, "titleOne": "Chat", "treOne": "Chat history,theme,wallpapers"},
      {"iconOne": Icons.notifications, "titleOne": "Notifications", "treOne": "Messages, group and others"},
      {"iconOne": Icons.help, "titleOne": "Help", "treOne": "Help center,contact us, privacy policy"},
      {"iconOne": Icons.mobiledata_off_outlined, "titleOne": "Storage and data", "treOne": "Network usage, stogare usage"},
      {"iconOne": Icons.person_add_alt, "titleOne": "Invite a friend", "treOne": ""},
    ],
  };
  static Map messageUser = {
    "messageUser": [
      {"iconOne": "assets/icons/botam_icon_one.png", "titleOne": "Camera", "treOne": ""},
      {"iconOne": "assets/icons/botam_icon_two.png", "titleOne": "Documents", "treOne": "Share your files"},
      {"iconOne": "assets/icons/botam_icon_three.png", "titleOne": "Create a poll", "treOne": "Create a poll for any querry"},
      {"iconOne": "assets/icons/botam_icon_four.png", "titleOne": "Media", "treOne": "Share photos and videos"},
      {"iconOne": "assets/icons/botam_icon_five.png", "titleOne": "Share photos and videos", "treOne": "Share your contacts"},
      {"iconOne": "assets/icons/botam_icon_six.png", "titleOne": "Location", "treOne": "Share your location"},
    ],
  };
  static Map musics = {
    "musics": [
      {"iconOne": "assets/icons/botam_icon_one.png", "titleOne": "Music One"},
      {"iconOne": "assets/icons/botam_icon_two.png", "titleOne": "Music Two"},
      {"iconOne": "assets/icons/botam_icon_three.png", "titleOne": "Music Three"},
      {"iconOne": "assets/icons/botam_icon_four.png", "titleOne": "Music Four"},
      {"iconOne": "assets/icons/botam_icon_five.png", "titleOne": "Music Five"},
      {"iconOne": "assets/icons/botam_icon_six.png", "titleOne": "Music Six"},
    ],
  };

  static List data = [
    "assets/images/group_two.png",
    "assets/images/group_three.png",
    "assets/images/group_four.png",
    "assets/images/group_five.png",
    "assets/images/group_six.png",
    "assets/images/group_seven.png",
    "assets/images/group_eight.png",
  ];

  static List<Map<String, dynamic>> data6 = [
    {
      "id": "Thought",
      "idtwo": "Make something unique and stylist",
      "value": false,
    },
    {
      "id": "UI/UX priority",
      "idtwo": "Design is intelligence made visible",
      "value": false,
    },
    {
      "id": "Design",
      "idtwo": "Everything is designed for you",
      "value": false,
    },
  ];
}
